#!/usr/bin/env node
// Generate `docs/src/SUMMARY.md`, mdBook's table of contents, from the page
// list in `crates/wasm/playground/docs.js`. That list is the single source for
// the playground panel, its search index, and the book, so a page registered
// once appears in all three.
//
//   node crates/wirescript/scripts/gen_book_summary.mjs           # write
//   node crates/wirescript/scripts/gen_book_summary.mjs --check   # CI gate
//
// Both modes fail on a `.md` in `docs/src/` that is registered nowhere;
// `--check` also fails when SUMMARY.md on disk is stale.

import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const docsDir = join(repoRoot, 'docs', 'src');
const summaryPath = join(docsDir, 'SUMMARY.md');
const docsJs = join(repoRoot, 'crates', 'wasm', 'playground', 'docs.js');

const { DOC_MANIFEST, DOC_PAGES, DOC_TITLES } = await import(pathToFileURL(docsJs).href);

// `DOC_MANIFEST` paths are site-relative (`docs/syntax.md`); the book's are
// relative to `docs/src`.
const fileOf = (page) => {
  const path = DOC_MANIFEST[page];
  return path ? path.replace(/^docs\//, '') : null;
};

const lines = ['<!-- Generated by scripts/gen_book_summary.mjs. Do not edit. -->', ''];
const covered = new Set();
for (const page of DOC_PAGES) {
  const file = fileOf(page);
  // `Playground` is the panel's own inline help, with no file to link.
  if (!file) continue;
  covered.add(file);
  const title = DOC_TITLES[page] || page;
  // A prefix chapter (no bullet) is what mdBook renders at `/docs/` itself.
  if (file === 'README.md' && lines.length === 2) {
    lines.push(`[${title}](README.md)`, '');
    continue;
  }
  lines.push(`- [${title}](${file})`);
}
lines.push('');

// CHANGELOG.md is staged in by the build, not tracked here.
const onDisk = readdirSync(docsDir)
  .filter((f) => f.endsWith('.md') && f !== 'SUMMARY.md' && f !== 'CHANGELOG.md')
  .sort();
const unregistered = onDisk.filter((f) => !covered.has(f));
if (unregistered.length) {
  console.error(
    `gen_book_summary: ${unregistered.join(', ')} in docs/src/ is not registered in ` +
      `crates/wasm/playground/docs.js. Add it to DOC_MANIFEST, DOC_PAGES and DOC_TITLES ` +
      `so it appears in both the playground panel and the book.`,
  );
  process.exit(1);
}

const next = lines.join('\n');
if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(summaryPath, 'utf8');
  } catch {
    /* missing counts as stale */
  }
  if (current !== next) {
    console.error('gen_book_summary: docs/src/SUMMARY.md is stale, run `just doc-summary`');
    process.exit(1);
  }
  console.log(`gen_book_summary: SUMMARY.md up to date (${covered.size} pages)`);
} else {
  writeFileSync(summaryPath, next);
  console.log(`gen_book_summary: wrote docs/src/SUMMARY.md (${covered.size} pages)`);
}
