#!/usr/bin/env node
// Generate `docs/assets/wirescript-hljs.js`, the highlight.js language mdBook
// loads for ```wirescript blocks, from the Monarch grammar the playground
// already uses (`crates/wasm/playground/monarch.js`). One keyword list feeds
// the editor and the book.
//
//   node crates/wirescript/scripts/gen_hljs_lang.mjs           # write
//   node crates/wirescript/scripts/gen_hljs_lang.mjs --check   # CI gate

import { readFileSync, mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const outPath = join(repoRoot, 'docs', 'assets', 'wirescript-hljs.js');
const monarch = join(repoRoot, 'crates', 'wasm', 'playground', 'monarch.js');

const { monarchLanguage: g } = await import(pathToFileURL(monarch).href);

const words = (xs) => [...new Set(xs)].sort().join(' ');

const body = `// Generated by scripts/gen_hljs_lang.mjs from monarch.js. Do not edit.
(function () {
  if (typeof hljs === 'undefined') return;

  hljs.registerLanguage('wirescript', function (hljs) {
    return {
      name: 'Wirescript',
      keywords: {
        keyword: ${JSON.stringify(words(g.keywords))},
        type: ${JSON.stringify(words(g.typeKeywords))},
        built_in: ${JSON.stringify(words([...g.builtins, ...g.events]))},
        literal: ${JSON.stringify(words(g.constants || []))},
      },
      contains: [
        hljs.C_LINE_COMMENT_MODE,
        hljs.C_BLOCK_COMMENT_MODE,
        hljs.C_NUMBER_MODE,
        // Interpolation is \${...} inside an ordinary string.
        {
          className: 'string',
          begin: '"', end: '"',
          illegal: '\\\\n',
          contains: [
            { begin: '\\\\\\\\.' },
            { className: 'subst', begin: '\\\\\\${', end: '}' },
          ],
        },
        { className: 'string', begin: "'", end: "'", illegal: '\\\\n' },
        // Annotations: @layout("code"), @closed, @label(...)
        { className: 'meta', begin: '@[A-Za-z_][A-Za-z0-9_]*' },
        // Asset and prefab references: $Item/Foo, $./file.brz
        { className: 'symbol', begin: '\\\\\\$[A-Za-z0-9_./-]+' },
      ],
    };
  });

  // mdBook ships highlight.js 10.x, whose entry point is highlightBlock.
  // highlightElement is the 11.x name, tried first so a future mdBook works.
  var highlight = hljs.highlightElement || hljs.highlightBlock;
  if (!highlight) return;

  // These blocks are already highlighted by the time this runs, and with the
  // WRONG grammar: an unregistered language sends hljs 10 down its
  // auto-detection path. Flatten back to plain text first, or the stale spans
  // survive underneath the new ones.
  var blocks = document.querySelectorAll('code.language-wirescript');
  for (var i = 0; i < blocks.length; i++) {
    var el = blocks[i];
    el.textContent = el.textContent;
    el.className = el.className.replace(/\\bhljs\\b/g, '').trim();
    el.removeAttribute('data-highlighted');
    highlight.call(hljs, el);
  }

})();
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(outPath, 'utf8');
  } catch {
    /* missing counts as stale */
  }
  if (current !== body) {
    console.error('gen_hljs_lang: docs/assets/wirescript-hljs.js is stale, run `just doc-hljs`');
    process.exit(1);
  }
  console.log('gen_hljs_lang: wirescript-hljs.js up to date');
} else {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body);
  console.log(
    `gen_hljs_lang: wrote docs/assets/wirescript-hljs.js ` +
      `(${g.keywords.length} keywords, ${g.typeKeywords.length} types, ` +
      `${g.builtins.length + g.events.length} builtins)`,
  );
}
