#!/usr/bin/env node
// Generate probes/verify_semantics.ws from data/gate_semantics.json: an
// in-game circuit that re-asserts every certified case with real gates.
//   node scripts/gen_verifier.mjs [--table data/gate_semantics.json] [--out probes/verify_semantics.ws]
import { readFileSync, writeFileSync } from 'fs';
import { pathToFileURL } from 'url';

const SHORT = cls => cls.replace(/^BrickComponentType_WireGraph_(Expr|Exec)_/, '');

// Escape arbitrary text for INSIDE a wirescript double-quoted interpolated
// string: backslash, quote, and the interpolation opener (lexer supports
// \, \", \$; JSON.stringify is unsafe here — its \uXXXX escapes are not
// valid wirescript escapes).
function wsEscape(s) {
  return String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$\{/g, '\\${')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t')
    .replace(/\r/g, '\\r');
}
function wsString(s) {
  return '"' + wsEscape(s) + '"';
}

// Wirescript literal for a probed operand.
function lit({ variant, value }) {
  if (variant === 'str') return wsString(value);
  if (variant === 'float') {
    if (/nan/i.test(value)) return '(0.0 / 0.0)';
    if (/^-?inf$/i.test(value)) return `(${value.startsWith('-') ? '-1.0' : '1.0'} / 0.0)`;
    return value.includes('.') ? value : `${value}.0`;
  }
  return value; // int, bool
}

// NOTE: LogicalXOR maps to the dedicated `^^` operator, NOT `!=` — `!=`
// lowers to CompareNotEqual, a different gate class (see
// probes/gate_semantics.ws). CompareLessOrEqual / CompareGreaterOrEqual
// (WITH "Or") match the SHORT() spelling of the real gate class names, per
// Task 4's landed GATE_CLASS table in gen_semantics.mjs.
const BIN_OP = {
  CompareEqual: '==', CompareNotEqual: '!=',
  LogicalAND: '&&', LogicalOR: '||', LogicalXOR: '^^',
  CompareLess: '<', CompareLessOrEqual: '<=',
  CompareGreater: '>', CompareGreaterOrEqual: '>=',
  MathAdd: '+', MathSubtract: '-', MathMultiply: '*',
  MathDivide: '/', MathModulo: '%',
};

export function generateVerifier(table) {
  const out = [];
  const cases = [];
  let skippedUnwired = 0;
  let skippedNan = 0;
  for (const [cls, entry] of Object.entries(table.gates)) {
    const short = SHORT(cls);
    for (const c of entry.cases) {
      if (c.inputs.some(i => i === 'unwired')) { skippedUnwired++; continue; }
      // An EQ assertion against an expected NaN can never pass under IEEE
      // compare (and the game's NaN== semantics are exactly what the probe
      // certifies) — skip rather than generate an always-red assertion.
      if (c.output.variant === 'float' && /nan/i.test(c.output.value)) { skippedNan++; continue; }
      cases.push({ short, c });
    }
  }
  out.push('/// GENERATED by scripts/gen_verifier.mjs — do not edit.');
  out.push(`/// Verifies data/gate_semantics.json (build ${table.build}).`);
  if (skippedUnwired) out.push(`/// skipped ${skippedUnwired} unwired cases (not expressible as assertions).`);
  if (skippedNan) out.push(`/// skipped ${skippedNan} NaN-expected cases (EQ on NaN cannot assert; certified by the probe only).`);
  out.push('let grid = ReadBrickGrid()');
  out.push('');
  out.push('mod failLine(msg: string) {');
  out.push('  PrintToConsole(msg)');
  out.push('  await SleepTicks(_, delay = 1)');
  out.push('}');
  out.push('');
  out.push('on grid {');
  out.push(`  PrintToConsole("VERIFIER v${table.probeVersion} table ${table.build}")`);
  out.push('  var pass: int = 0');
  out.push(`  var total: int = ${cases.length}`);
  let n = 0;
  for (const { short, c } of cases) {
    n++;
    const exp = lit(c.output);
    const desc = wsEscape(`${short} ${c.inputs.map(i => `${i.variant}:${i.value}`).join(' ')}`);
    if (short === 'Branch') {
      out.push(`  var got${n}: string = ""`);
      out.push(`  if Opaque(${lit(c.inputs[0])}) { got${n} = "A" } else { got${n} = "B" }`);
      out.push(`  if got${n} == ${lit(c.output)} { pass = pass + 1 } else { failLine("FAIL ${desc} expected ${c.output.value} got \${got${n}}") }`);
    } else if (short === 'Select') {
      out.push(`  let got${n} = if Opaque(${lit(c.inputs[0])}) then 111 else 222`);
      out.push(`  if got${n} == ${exp} { pass = pass + 1 } else { failLine("FAIL ${desc} expected ${c.output.value} got \${got${n}}") }`);
    } else if (short === 'LogicalNOT') {
      out.push(`  let got${n} = !Opaque(${lit(c.inputs[0])})`);
      out.push(`  if got${n} == ${exp} { pass = pass + 1 } else { failLine("FAIL ${desc} expected ${c.output.value} got \${got${n}}") }`);
    } else {
      const op = BIN_OP[short];
      if (!op) throw new Error(`no operator mapping for ${short}`);
      out.push(`  let got${n} = Opaque(${lit(c.inputs[0])}) ${op} Opaque(${lit(c.inputs[1])})`);
      out.push(`  if got${n} == ${exp} { pass = pass + 1 } else { failLine("FAIL ${desc} expected ${c.output.value} got \${got${n}}") }`);
    }
  }
  out.push('  PrintToConsole("VERIFY ${pass}/${total}")');
  out.push('}');
  return out.join('\n') + '\n';
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const args = process.argv.slice(2);
  const tablePath = args.includes('--table') ? args[args.indexOf('--table') + 1] : 'data/gate_semantics.json';
  const outPath = args.includes('--out') ? args[args.indexOf('--out') + 1] : 'probes/verify_semantics.ws';
  const table = JSON.parse(readFileSync(tablePath, 'utf8'));
  const ws = generateVerifier(table);
  writeFileSync(outPath, ws);
  console.log(`wrote ${outPath}`);
}
