//! Wire port registry — all known Brickadia gate wire port names.
//!
//! The `WirePort` enum has one variant per port name from the gate
//! inventory. Rust picks the optimal discriminant size automatically
//! (u8 at 239 variants, scales if more are added).

macro_rules! wire_ports {
    ( $( $variant:ident = $str_name:literal ),* $(,)? ) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub enum WirePort {
            $( $variant, )*
            /// Synthetic layout-only edge (not a real Brickadia port).
            Layout,
        }

        impl WirePort {
            pub fn as_str(self) -> &'static str {
                match self {
                    $( WirePort::$variant => $str_name, )*
                    WirePort::Layout => "_Layout",
                }
            }

            pub fn from_name(name: &str) -> WirePort {
                match name {
                    $( $str_name => WirePort::$variant, )*
                    "_Layout" => WirePort::Layout,
                    _ => panic!("unknown wire port: {name}"),
                }
            }

            pub fn all_names() -> &'static [&'static str] {
                static NAMES: &[&str] = &[ $( $str_name, )* ];
                NAMES
            }
        }

        impl std::fmt::Display for WirePort {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_str())
            }
        }
    };
}

wire_ports! {
    // Ports added for the array / controller / character / gamemode builtins.
    BDescending = "bDescending",
    BDetectBricks = "bDetectBricks",
    BDetectPlayers1 = "bDetectPlayers1",
    BDetectPlayers2 = "bDetectPlayers2",
    BDetectPlayers3 = "bDetectPlayers3",
    BDetectPlayers4 = "bDetectPlayers4",
    BDetectPhysics = "bDetectPhysics",
    BDetectMap = "bDetectMap",
    BIgnoreOwningGrid = "bIgnoreOwningGrid",
    AdditionalIgnoredEntities = "AdditionalIgnoredEntities",
    IndexA = "IndexA",
    IndexB = "IndexB",
    Size = "Size",
    Count = "Count",
    SourceRef = "SourceRef",
    DeltaTime = "DeltaTime",
    Uptime = "Uptime",
    Tolerance = "Tolerance",
    Target = "Target",
    SmoothTime = "SmoothTime",
    Function = "Function",
    Duration = "Duration",
    Arrived = "Arrived",
    PermissionName = "PermissionName",
    PermissionTagStr = "PermissionTagStr",
    RoleName = "RoleName",
    Restart = "Restart",
    Pause = "Pause",
    Resume = "Resume",
    DestroyAll = "DestroyAll",
    Time = "Time",
    Expired = "Expired",
    UserName = "UserName",
    UserId = "UserId",
    DisplayName = "DisplayName",
    BHasPermission = "bHasPermission",
    BHasRole = "bHasRole",
    // Ports added for the builtins (messaging, tags, audio,
    // quaternions, inventory family, damage/zone events).
    Title = "Title",
    Tag = "Tag",
    Query = "Query",
    BFlashIfUnchanged = "bFlashIfUnchanged",
    W = "W",
    OnChanged = "OnChanged",
    OnRisingEdge = "OnRisingEdge",
    OnFallingEdge = "OnFallingEdge",
    BPulseOnChange = "bPulseOnChange",
    Item = "Item",
    ItemType = "ItemType",
    EntityType = "EntityType",
    BrickAsset = "BrickAsset",
    ProceduralSize = "ProceduralSize",
    DamageMultiplier = "DamageMultiplier",
    ItemNameOverride = "ItemNameOverride",
    ItemScale = "ItemScale",
    ProjectileOverride = "ProjectileOverride",
    ProjectileType = "ProjectileType",
    WorldPosition = "WorldPosition",
    BResult = "bResult",
    Prefab = "Prefab",
    WeaponSpeedMultiplier = "WeaponSpeedMultiplier",
    Attacker = "Attacker",
    AttackerWeapon = "AttackerWeapon",
    AttackerWeaponName = "AttackerWeaponName",
    Projectile = "Projectile",
    Weapon = "Weapon",
    WeaponName = "WeaponName",
    BIsTrusted = "bIsTrusted",
    BCanRespawn = "bCanRespawn",
    DamageLimit = "DamageLimit",
    Amount = "Amount",
    BFrozen = "bFrozen",
    Name = "Name",
    Player = "Player",
    BTeamWinsInstead = "bTeamWinsInstead",
    BPinPlayerToTeam = "bPinPlayerToTeam",
    BPinned = "bPinned",
    A = "A",
    Alpha = "Alpha",
    Axis = "Axis",
    ColorA = "ColorA",
    ColorB = "ColorB",
    CollisionChannel = "CollisionChannel",
    From = "From",
    Hex = "Hex",
    Pitch = "Pitch",
    Roll = "Roll",
    To = "To",
    Yaw = "Yaw",
    AggroRange = "AggroRange",
    Agression = "Agression",
    AnchorX = "Anchor.X",
    AnchorY = "Anchor.Y",
    Angle = "Angle",
    AngularVelocity = "AngularVelocity",
    Arguments = "Arguments",
    ArrayVarRef = "ArrayVarRef",
    AttackDamageMultiplier = "AttackDamageMultiplier",
    AttackMovementAmount = "AttackMovementAmount",
    AudioDescriptor = "AudioDescriptor",
    B = "B",
    Base = "Base",
    Blend = "Blend",
    BotName = "BotName",
    BotWeapon = "BotWeapon",
    BrickGrid = "BrickGrid",
    CenterOfSteering = "CenterOfSteering",
    Character = "Character",
    CharacterThatJustHit = "CharacterThatJustHit",
    ConsoleTag = "ConsoleTag",
    ControlDriveAndSteer = "Control_DriveAndSteer",
    Controller = "Controller",
    CorpseTimeout = "CorpseTimeout",
    CustomMass = "CustomMass",
    CustomMassVerticalOffset = "CustomMassVerticalOffset",
    Damage = "Damage",
    DataIn1 = "DataIn1",
    DataIn2 = "DataIn2",
    DataIn3 = "DataIn3",
    DataIn4 = "DataIn4",
    DataIn5 = "DataIn5",
    DataIn6 = "DataIn6",
    DataIn7 = "DataIn7",
    DataIn8 = "DataIn8",
    DataOut1 = "DataOut1",
    DataOut2 = "DataOut2",
    DataOut3 = "DataOut3",
    DataOut4 = "DataOut4",
    DataOut5 = "DataOut5",
    DataOut6 = "DataOut6",
    DataOut7 = "DataOut7",
    DataOut8 = "DataOut8",
    EventName = "EventName",
    BOnlyReceiveFromSameOwner = "bOnlyReceiveFromSameOwner",
    Delimiter = "Delimiter",
    Destination = "Destination",
    Direction = "Direction",
    Distance = "Distance",
    DistanceToTarget = "DistanceToTarget",
    DriveAccelPowerMult = "DriveAcceleratingPowerMultiplier",
    DriveBrakePowerMult = "DriveBrakingPowerMultiplier",
    DriveDampingMult = "DriveDampingMultiplier",
    DriveInterpSpeed = "DriveInterpSpeed",
    DriveSpeed = "DriveSpeed",
    Entity = "Entity",
    Exec = "Exec",
    ExecA = "ExecA",
    ExecB = "ExecB",
    ExecIn = "ExecIn",
    ExecOut = "ExecOut",
    ExecOutA = "ExecOutA",
    ExecOutB = "ExecOutB",
    ExitOffset = "ExitOffset",
    Exponent = "Exponent",
    FocusAzimuth = "FocusAzimuth",
    FocusCharacter = "FocusCharacter",
    FontColor = "FontColor",
    FontSize = "FontSize",
    FormatString = "FormatString",
    G = "G",
    GunSkill = "GunSkill",
    HealthMultiplier = "HealthMultiplier",
    HintText = "HintText",
    HintTitle = "HintTitle",
    Hit = "Hit",
    HitDistance = "HitDistance",
    HitEntity = "HitEntity",
    HitLocation = "HitLocation",
    HitNormal = "HitNormal",
    IgnoreEntity = "IgnoreEntity",
    Index = "Index",
    InnerRadius = "InnerRadius",
    Input = "Input",
    InputA = "InputA",
    InputB = "InputB",
    InputC = "InputC",
    InputD = "InputD",
    InputE = "InputE",
    InputF = "InputF",
    InputForward = "InputForward",
    InputG = "InputG",
    InputRight = "InputRight",
    InteractSound = "InteractSound",
    ItemTypeIfItem = "ItemTypeIfItem",
    Jumpyness = "Jumpyness",
    Justification = "Justification",
    Key = "Key",
    Left = "Left",
    Length = "Length",
    Lifetime = "Lifetime",
    Limit = "Limit",
    LinearVelocity = "LinearVelocity",
    ManualInputDrive = "ManualInput_Drive",
    ManualInputSteer = "ManualInput_Steer",
    Mass = "Mass",
    MassOffset = "MassOffset",
    MassSize = "MassSize",
    Max = "Max",
    MaxDistance = "MaxDistance",
    Message = "Message",
    Min = "Min",
    Miss = "Miss",
    MoveTarget = "MoveTarget",
    MovementAmount = "MovementAmount",
    MovementGoalDummy = "MovementGoalDummy",
    MovementRandomness = "MovementRandomness",
    NonFocusAzimuth = "NonFocusAzimuth",
    NonFocusVolumeAtten = "NonFocusVolumeAttenuation",
    OccupantCount = "OccupantCount",
    OnTime = "OnTime",
    Origin = "Origin",
    OutlineColor = "OutlineColor",
    OutlineSize = "OutlineSize",
    Output = "Output",
    OutputB = "OutputB",
    PitchMultiplier = "PitchMultiplier",
    PositionX = "Position.X",
    PositionY = "Position.Y",
    Prefix = "Prefix",
    PressCount = "PressCount",
    PressSound = "PressSound",
    PromptCustomLabel = "PromptCustomLabel",
    R = "R",
    RerInput = "RER_Input",
    RerOutput = "RER_Output",
    Radius = "Radius",
    ReactionTime = "ReactionTime",
    ReleaseSound = "ReleaseSound",
    RepeatTime = "RepeatTime",
    RepeatVariance = "RepeatVariance",
    Replacement = "Replacement",
    Reset = "Reset",
    RespawnTime = "RespawnTime",
    Right = "Right",
    Rotation = "Rotation",
    RoundNumber = "RoundNumber",
    RunSpeed = "RunSpeed",
    Scalar = "Scalar",
    ScaleX = "Scale.X",
    ScaleY = "Scale.Y",
    Search = "Search",
    SecondsToWait = "SecondsToWait",
    Seed = "Seed",
    Separator = "Separator",
    SittingCharacter = "SittingCharacter",
    SkinDummy = "SkinDummy",
    Slot = "Slot",
    Source = "Source",
    SpawnOffset = "SpawnOffset",
    SpawnOffsetRotation = "SpawnOffsetRotation",
    SpawnVelocity = "SpawnVelocity",
    SpawnedCharacter = "SpawnedCharacter",
    Start = "Start",
    SteerInterpSpeed = "SteerInterpSpeed",
    SteerLimitDegree = "SteerLimitDegree",
    SteerPowerMult = "SteerPowerMultiplier",
    Suffix = "Suffix",
    TankSteerSpeedMult = "TankSteerSpeedMultiplier",
    Team = "Team",
    TeamCollisionChannel = "TeamCollisionChannel",
    TeamName = "TeamName",
    Text = "Text",
    TextId = "TextId",
    TextIdOut = "TextIdOut",
    ThisDestination = "ThisDestination",
    TicksToWait = "TicksToWait",
    Transition = "Transition",
    Easing = "Easing",
    Value = "Value",
    VarRef = "VarRef",
    Vector = "Vector",
    VolumeMultiplier = "VolumeMultiplier",
    WaterDriveForce = "WaterDriveForce",
    WaterSteeringForce = "WaterSteeringForce",
    Winner = "Winner",
    X = "X",
    Y = "Y",
    Z = "Z",
    ZeroSecondsToWait = "ZeroSecondsToWait",
    ZeroTicksToWait = "ZeroTicksToWait",
    Zone = "Zone",
    ZoneEndDistance = "ZoneEndDistance",
    ZoneRef = "ZoneRef",
    ZoneStartDistance = "ZoneStartDistance",
    BActiveBoi = "bActiveBot",
    BAllowNearbyInteraction = "bAllowNearbyInteraction",
    BBackVision = "bBackVision",
    BCanJump = "bCanJump",
    BCanTargetBots = "bCanTargetBots",
    BCanTargetPlayers = "bCanTargetPlayers",
    BCaseSensitive = "bCaseSensitive",
    BCollisionEnabledPlayer = "bCollisionEnabled_Player",
    BCollisionEnabledPlayer1 = "bCollisionEnabled_Player1",
    BCollisionEnabledPlayer2 = "bCollisionEnabled_Player2",
    BCollisionEnabledPlayer3 = "bCollisionEnabled_Player3",
    BCond = "bCond",
    BDeleteBot = "bDeleteBot",
    BEnable = "bEnable",
    BEnableManualControl = "bEnableManualControl",
    BEnableRepeat = "bEnableRepeat",
    BEnabled = "bEnabled",
    BHeld = "bHeld",
    BHiddenInteraction = "bHiddenInteraction",
    BInput = "bInput",
    BInputA = "bInputA",
    BInputB = "bInputB",
    BIsBuildingZone = "bIsBuildingZone",
    BIsEmpty = "bIsEmpty",
    BIsLooseZone = "bIsLooseZone",
    BIsOccupied = "bIsOccupied",
    BIsShareZone = "bIsShareZone",
    BFound = "bFound",
    BJustHit = "bJustHit",
    BManualInputBrake = "bManualInput_Brake",
    BOccupied = "bOccupied",
    BOutOfBounds = "bOutOfBounds",
    BOutput = "bOutput",
    BPermissionEnable = "bPermissionEnable",
    BPlay = "bPlay",
    BPressedJump = "bPressedJump",
    BPulseOnFallingEdge = "bPulseOnFallingEdge",
    BPulseOnRisingEdge = "bPulseOnRisingEdge",
    BRelative = "bRelative",
    BRotatePlayerGravityOnSpawn = "bRotatePlayerGravityOnSpawn",
    BSelectB = "bSelectB",
    BSpatialization = "bSpatialization",
    BSpawnEnable = "bSpawnEnable",
    BSwap = "bSwap",
    BTankSteering = "bTankSteering",
    BTeamCollision = "bTeamCollision",
    BTeamCollision1 = "bTeamCollision1",
    BTeamCollision2 = "bTeamCollision2",
    BTeamCollision3 = "bTeamCollision3",
    BVisionRaycasting = "bVisionRaycasting",
    // PlayerState refactor + new-build gate additions.
    PlayerState = "PlayerState",
    // Reworked InputSplitter output ports.
    InputUp = "InputUp",
    InputPitch = "InputPitch",
    InputYaw = "InputYaw",
    InputRoll = "InputRoll",
    InputMouseWheel = "InputMouseWheel",
    BPressedC = "bPressedC",
    BPressedE = "bPressedE",
    BPressedQ = "bPressedQ",
    BPressedLeftMouse = "bPressedLeftMouse",
    BPressedRightMouse = "bPressedRightMouse",
    // Reworked DisplayText styling ports.
    Skew = "Skew",
    LetterSpacing = "LetterSpacing",
    LineHeight = "LineHeight",
    WrapWidth = "WrapWidth",
    ZOrder = "ZOrder",
    ShadowColor = "ShadowColor",
    BMiteredOutline = "bMiteredOutline",
    HitColor = "HitColor",
    // Entity/character gate additions.
    Point = "Point",
    Speed = "Speed",
    Resource = "Resource",
    // Expr gate additions (Remap, IntegerToEnum, codepoint, date).
    InputMin = "InputMin",
    InputMax = "InputMax",
    OutputMin = "OutputMin",
    OutputMax = "OutputMax",
    BWrap = "bWrap",
    Codepoint = "Codepoint",
    BSuccess = "bSuccess",
    UnixEpoch = "UnixEpoch",
    Format = "Format",
    BUseUTC = "bUseUTC",
    Location = "Location",
    SpreadConeAngle = "SpreadConeAngle",
    TagFilter = "TagFilter",
    // ColorConvert data-only enum fields (color-space selection).
    FromSpace = "FromSpace",
    ToSpace = "ToSpace",
    // MapVar variable family.
    MapVarRef = "MapVarRef",
    // SortMultiple parallel array refs.
    ArrayVarRef2 = "ArrayVarRef2",
    ArrayVarRef3 = "ArrayVarRef3",
    ArrayVarRef4 = "ArrayVarRef4",
    ArrayVarRef5 = "ArrayVarRef5",
    ArrayVarRef6 = "ArrayVarRef6",
    ArrayVarRef7 = "ArrayVarRef7",
    ArrayVarRef8 = "ArrayVarRef8",
    // Full inventory port coverage (vehicle/aero/pickup/light/water/etc.
    // internal components, plus reworked string/displaytext ports). Kept
    // exhaustive so lower_call can pull any gate's catalog ports without a
    // from_name panic.
    ActiveDamping = "ActiveDamping",
    AerodynamicDirection = "AerodynamicDirection",
    AirStrafeControl = "AirStrafeControl",
    Anchor = "Anchor",
    ArcadeAeroAuthorityFadeEndSpeed = "ArcadeAeroAuthorityFadeEndSpeed",
    ArcadeAeroAuthorityFadeStartSpeed = "ArcadeAeroAuthorityFadeStartSpeed",
    ArcadeAirGripResponseTime = "ArcadeAirGripResponseTime",
    ArcadeMaxLateralAccelerationGs = "ArcadeMaxLateralAccelerationGs",
    ArcadePitchRate = "ArcadePitchRate",
    ArcadeResponseTime = "ArcadeResponseTime",
    ArcadeRollRate = "ArcadeRollRate",
    ArcadeYawRate = "ArcadeYawRate",
    BeginTouchSound = "BeginTouchSound",
    Billboard = "Billboard",
    Brightness = "Brightness",
    CameraOrigin = "CameraOrigin",
    CameraOriginOffset = "CameraOriginOffset",
    Color = "Color",
    CurrentAngle = "CurrentAngle",
    CurrentPosition = "CurrentPosition",
    Damping = "Damping",
    Deflection = "Deflection",
    DragCoefficient = "DragCoefficient",
    DrivePower = "DrivePower",
    EndTouchSound = "EndTouchSound",
    ExecDown = "ExecDown",
    ExecOutDown = "ExecOutDown",
    Face = "Face",
    FireRate = "FireRate",
    FireSound = "FireSound",
    FlightHandling = "FlightHandling",
    FlightInvertXOverride = "FlightInvertXOverride",
    FlightInvertYOverride = "FlightInvertYOverride",
    FlightTopSpeed = "FlightTopSpeed",
    Font = "Font",
    Force = "Force",
    ForceApplication = "ForceApplication",
    ForceLimit = "ForceLimit",
    GlideTrimStrength = "GlideTrimStrength",
    GlideTrimTargetSpeedMultiplier = "GlideTrimTargetSpeedMultiplier",
    GraffitiAngleLimit = "GraffitiAngleLimit",
    GraffitiDepthLimit = "GraffitiDepthLimit",
    GraffitiLayer = "GraffitiLayer",
    HorizontalSteeringRollMix = "HorizontalSteeringRollMix",
    HorizontalSteeringYawMix = "HorizontalSteeringYawMix",
    InnerConeAngle = "InnerConeAngle",
    Instigator = "Instigator",
    InterpMode = "InterpMode",
    IntervalSeconds = "IntervalSeconds",
    JointDistance = "JointDistance",
    Kerning = "Kerning",
    KeyboardSteeringRollMix = "KeyboardSteeringRollMix",
    KeyboardSteeringYawMix = "KeyboardSteeringYawMix",
    Killer = "Killer",
    KillerWeapon = "KillerWeapon",
    KillerWeaponName = "KillerWeaponName",
    LiftCoefficient = "LiftCoefficient",
    LiftMultiplier = "LiftMultiplier",
    LimitAngle = "LimitAngle",
    LineOffset = "LineOffset",
    LocationInterpMode = "LocationInterpMode",
    LocationMaxSpeed = "LocationMaxSpeed",
    LocationSmoothTime = "LocationSmoothTime",
    ManualControlMode = "ManualControlMode",
    ManualInputPitch = "ManualInput_Pitch",
    ManualInputRoll = "ManualInput_Roll",
    MassDistribution = "MassDistribution",
    Material = "Material",
    MaterialAlpha = "MaterialAlpha",
    MaterialSlider = "MaterialSlider",
    MaxDeflection = "MaxDeflection",
    MaxForce = "MaxForce",
    MaxReplacements = "MaxReplacements",
    NumberOfShots = "NumberOfShots",
    Occurrence = "Occurrence",
    Offset = "Offset",
    OffsetLocation = "OffsetLocation",
    OffsetRotation = "OffsetRotation",
    OnFired = "OnFired",
    OuterConeAngle = "OuterConeAngle",
    Outline = "Outline",
    OutlineWidth = "OutlineWidth",
    PhysicalPitchDampingResponseTime = "PhysicalPitchDampingResponseTime",
    PhysicalRollDampingResponseTime = "PhysicalRollDampingResponseTime",
    PhysicalYawDampingResponseTime = "PhysicalYawDampingResponseTime",
    PickupAnimationAxis = "PickupAnimationAxis",
    PickupAnimationPhase = "PickupAnimationPhase",
    PickupBobHeight = "PickupBobHeight",
    PickupBobSpeed = "PickupBobSpeed",
    PickupClass = "PickupClass",
    PickupMeshColors = "PickupMeshColors",
    PickupMinigameResetRespawnDelay = "PickupMinigameResetRespawnDelay",
    PickupOffsetDirection = "PickupOffsetDirection",
    PickupOffsetDistance = "PickupOffsetDistance",
    PickupRespawnTime = "PickupRespawnTime",
    PickupRotation = "PickupRotation",
    PickupScale = "PickupScale",
    PickupSpinSpeed = "PickupSpinSpeed",
    Pivot = "Pivot",
    Play = "Play",
    Position = "Position",
    Power = "Power",
    ProjectileClass = "ProjectileClass",
    Pulse = "Pulse",
    RayTracingVisibility = "RayTracingVisibility",
    RepeatCount = "RepeatCount",
    RepeatDelay = "RepeatDelay",
    Role = "Role",
    RotationInterpMode = "RotationInterpMode",
    RotationMaxSpeed = "RotationMaxSpeed",
    RotationSmoothTime = "RotationSmoothTime",
    Scale = "Scale",
    ScaleMultiplier = "ScaleMultiplier",
    ScuffWidth = "ScuffWidth",
    SeatMode = "SeatMode",
    Shading = "Shading",
    ShadingWidth = "ShadingWidth",
    ShadowOffset = "ShadowOffset",
    Skin = "Skin",
    SpawnLocation = "SpawnLocation",
    SpawnMargin = "SpawnMargin",
    SpawnOffsetBias = "SpawnOffsetBias",
    SpawnedEntity = "SpawnedEntity",
    SpeedMultiplier = "SpeedMultiplier",
    StallAngle = "StallAngle",
    Steer = "Steer",
    SteerLimitSpeedFalloff = "SteerLimitSpeedFalloff",
    SteerPower = "SteerPower",
    Stop = "Stop",
    Strength = "Strength",
    SuspensionDamping = "SuspensionDamping",
    SuspensionLength = "SuspensionLength",
    SuspensionOffset = "SuspensionOffset",
    SuspensionStiffness = "SuspensionStiffness",
    TargetAngle = "TargetAngle",
    TargetAxis = "TargetAxis",
    TargetPosition = "TargetPosition",
    ThirdPersonCameraRotation = "ThirdPersonCameraRotation",
    ThirdPersonStartingZoom = "ThirdPersonStartingZoom",
    Throttle = "Throttle",
    ThrustMultiplier = "ThrustMultiplier",
    TopSpeed = "TopSpeed",
    TouchCount = "TouchCount",
    Typeface = "Typeface",
    WaterAbsorption = "WaterAbsorption",
    WaterFogAmbientColor = "WaterFogAmbientColor",
    WaterFogAmbientScale = "WaterFogAmbientScale",
    WaterFogIntensity = "WaterFogIntensity",
    WaterFogScatteringColor = "WaterFogScatteringColor",
    WaterFogScatteringScale = "WaterFogScatteringScale",
    WaterScattering = "WaterScattering",
    WeaponNameThatJustHit = "WeaponNameThatJustHit",
    WeaponThatJustHit = "WeaponThatJustHit",
    WheelFrictionMultiplier = "WheelFrictionMultiplier",
    WidthScale = "WidthScale",
    BAlignToWedge = "bAlignToWedge",
    BAllowEngineSteerCorrect = "bAllowEngineSteerCorrect",
    BAllowHeldItems = "bAllowHeldItems",
    BAnglesArePercentages = "bAnglesArePercentages",
    BAutoRight = "bAutoRight",
    BAutodiscoverAerodynamicSurfaces = "bAutodiscoverAerodynamicSurfaces",
    BAutodiscoverGyroscopes = "bAutodiscoverGyroscopes",
    BAutodiscoverThrusters = "bAutodiscoverThrusters",
    BAutodiscoverWheels = "bAutodiscoverWheels",
    BCanBrake = "bCanBrake",
    BCastShadows = "bCastShadows",
    BCollisionEnabled = "bCollisionEnabled",
    BCollisionEnabledInteraction = "bCollisionEnabled_Interaction",
    BCollisionEnabledPhysics = "bCollisionEnabled_Physics",
    BCollisionEnabledWeapon = "bCollisionEnabled_Weapon",
    BDetectEntities = "bDetectEntities",
    BDetectPlayers = "bDetectPlayers",
    BDetectProjectiles = "bDetectProjectiles",
    BDisableInWorldControlDiagnostics = "bDisableInWorldControlDiagnostics",
    BDiscoverable = "bDiscoverable",
    BDriveWhenNotAttachedToEngine = "bDriveWhenNotAttachedToEngine",
    BEnableAerodynamicRateDamping = "bEnableAerodynamicRateDamping",
    BEnableAirBraking = "bEnableAirBraking",
    BEnableGlideTrim = "bEnableGlideTrim",
    BFlipShading = "bFlipShading",
    BFlyingGroundControls = "bFlyingGroundControls",
    BForeground = "bForeground",
    BLimitAngle = "bLimitAngle",
    BMatchBrickShape = "bMatchBrickShape",
    BOverrideColor = "bOverrideColor",
    BOverrideOutlineColor = "bOverrideOutlineColor",
    BOverridePickupColors = "bOverridePickupColors",
    BPickupAnimationAxisLocal = "bPickupAnimationAxisLocal",
    BPickupAnimationEnabled = "bPickupAnimationEnabled",
    BPickupAutoDisableOnPickup = "bPickupAutoDisableOnPickup",
    BPickupEnabled = "bPickupEnabled",
    BPickupRespawnOnMinigameReset = "bPickupRespawnOnMinigameReset",
    BPositionsArePercentages = "bPositionsArePercentages",
    BRenderTranslucentWhenDisabled = "bRenderTranslucentWhenDisabled",
    BReversed = "bReversed",
    BRollCameraInThirdPerson = "bRollCameraInThirdPerson",
    BScaleCameraOriginOffsetWithZoom = "bScaleCameraOriginOffsetWithZoom",
    BSettled = "bSettled",
    BSharpCorners = "bSharpCorners",
    BSharpOutlines = "bSharpOutlines",
    BShowPickupEnabled = "bShowPickupEnabled",
    BSpawnLight = "bSpawnLight",
    BSpreadBiasedTowardsCenter = "bSpreadBiasedTowardsCenter",
    BStalling = "bStalling",
    BSteerEnabled = "bSteerEnabled",
    BStickyPlaneThrottle = "bStickyPlaneThrottle",
    BStopped = "bStopped",
    BSuspensionEnabled = "bSuspensionEnabled",
    BTouching = "bTouching",
    BUseBrickColor = "bUseBrickColor",
    BVisibility = "bVisibility",
    BWater = "bWater",
    BWelded = "bWelded",
    BWheelVisible = "bWheelVisible",
    // Constant-only gate-config data fields (settings menu, not wire inputs).
    BClampAlpha = "bClampAlpha",
    BLocalAim = "bLocalAim",
    BOnlyHitPlayerBodyParts = "bOnlyHitPlayerBodyParts",
    BOverrideColors = "bOverrideColors",
    BShortestPath = "bShortestPath",
    BlendSpace = "BlendSpace",
    MeshColors = "MeshColors",
    WeaponAmmoOverride = "WeaponAmmoOverride",
    // Vector2D composite sub-ports (DisplayText layout): each parent (`Position`,
    // `Anchor`, …) exposes two individually-wireable float sub-ports `X`/`Y`.
    // Position/Anchor/Scale axes reuse the (repurposed) former Controller_DisplayText
    // variants below; Pivot/ShadowOffset are new to the reworked gate.
    PivotX = "Pivot.X",
    PivotY = "Pivot.Y",
    ShadowOffsetX = "ShadowOffset.X",
    ShadowOffsetY = "ShadowOffset.Y",
}

#[cfg(test)]
mod tests {
    use super::WirePort;

    #[test]
    fn subport_wireports_round_trip() {
        for wp in [
            WirePort::PositionX,
            WirePort::PositionY,
            WirePort::AnchorX,
            WirePort::AnchorY,
            WirePort::ScaleX,
            WirePort::ScaleY,
            WirePort::PivotX,
            WirePort::PivotY,
            WirePort::ShadowOffsetX,
            WirePort::ShadowOffsetY,
        ] {
            assert!(
                wp.as_str().contains('.'),
                "sub-port name is dotted: {}",
                wp.as_str()
            );
            assert_eq!(WirePort::from_name(wp.as_str()), wp);
        }
    }
}
